### PR TITLE
Add start page parameter

### PR DESCRIPTION
**Pull request by slallum**
now you can run: `cylance_api.get_devices(start_page=5)` for example

### CODE REVIEW

**Comment by joedelsol** [comment]
I thought that was possible before and believe it is a good idea. I'll need to review how I thought that was working prior to these additions and make sure this isn't a duplicate.

**Comment by joedelsol** [comment]
Sorry for the delay! From my memory, the expectation was that by sending in 'page', you would be setting the 'start_page'. It looks to me that the loop that includes line 304 and 305 were incorrectly written as:
            for page in range(2,total_pages+1):
                updated_param = {"page":page}

If written as 
            for p in range(page,total_pages+1):
                updated_param = {"page":p}

It would work as planned and meet your goals. Your method is more readable and should not break any functionality. I'll come up with some tests and assuming it works as expected will pull it in. Thanks!

P.S. Did you have a real world example that required this functionality that you can share?

**Comment by slallum** [comment]
@joedelsol thanks!
I had a case where I ran my code in a container with low memory, so I had to batch the devices and handle a few pages in each iteration (instead of getting all of them at once and crash the container).

**Comment by joedelsol** [comment]
Thanks for catching this and contributing!

**Pull request merged**
