### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ebourne**
update docs to reflect source code changes.

### CODE REVIEW

**Comment by joedelsol** [comment]
Thanks for catching that!

**Comment by ebourne** [comment]
ha!  wasn't sure anyone would ever merge this in...
hows the world outside cylance/blackberry?
cheersed
    On Monday, March 20, 2023 at 04:33:03 p.m. EDT, Joe Delsol ***@***.***> wrote:  
 
 


Thanks for catching that!

**Comment by rpermeh** [comment]
Is anyone still at bb running this?Sent from iPhoneOn Mar 21, 2023, at 7:16 AM, Ed Bourne ***@***.***> wrote:﻿
 ha!  wasn't sure anyone would ever merge this in...
hows the world outside cylance/blackberry?
cheersed
    On Monday, March 20, 2023 at 04:33:03 p.m. EDT, Joe Delsol ***@***.***> wrote:  
 
 


Thanks for catching that!

**Comment by ebourne** [comment]
yeah, sort of.  There is an open source group, and the team I'm on  (developer relations) is still doing things with Cylance rest api's with ISV's that want to.  Haven't had a customer ask me lately though.

cheersed
    On Tuesday, March 21, 2023 at 10:23:14 a.m. EDT, rpermeh ***@***.***> wrote:  
 
 

Is anyone still at bb running this?Sent from iPhoneOn Mar 21, 2023, at 7:16 AM, Ed Bourne ***@***.***> wrote:﻿
 ha!  wasn't sure anyone would ever merge this in...
hows the world outside cylance/blackberry?
cheersed
 On Monday, March 20, 2023 at 04:33:03 p.m. EDT, Joe Delsol ***@***.***> wrote: 
 
 


Thanks for catching that!

**Comment by rpermeh** [comment]
Rock on!Sent from iPhoneOn Mar 21, 2023, at 7:26 AM, Ed Bourne ***@***.***> wrote:﻿
 yeah, sort of.  There is an open source group, and the team I'm on  (developer relations) is still doing things with Cylance rest api's with ISV's that want to.  Haven't had a customer ask me lately though.

cheersed
    On Tuesday, March 21, 2023 at 10:23:14 a.m. EDT, rpermeh ***@***.***> wrote:  
 
 

Is anyone still at bb running this?Sent from iPhoneOn Mar 21, 2023, at 7:16 AM, Ed Bourne ***@***.***> wrote:﻿
 ha!  wasn't sure anyone would ever merge this in...
hows the world outside cylance/blackberry?
cheersed
 On Monday, March 20, 2023 at 04:33:03 p.m. EDT, Joe Delsol ***@***.***> wrote: 
 
 


Thanks for catching that!

**Comment by joedelsol** [comment]
Funny, I was not sure if there was anyone besides myself that could. 

Funny to see you are also still connected to this repo! Looks like you are doing fun things..

I’m doing good stuff at a Series A API Security company.

Ed,
Do you want to give us a couple accounts to add to this, so you are not looking for ghosts to merge, etc? Also, this is pushed to pypi; https://pypi.org/project/cyapi/

The doc error is over there, too.

I thought this project was getting replaced years ago. I knew about the issue you pushed, but had bitten off a documentation project that got away from me..  

Let me know how I can help.

~~
Joe Delsol
916-802-7606

**Comment by ebourne** [comment]
yes, please add me ebourne - Overview 

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
ebourne - Overview

ebourne has 5 repositories available. Follow their code on GitHub.
 |

 |

 |

and my colleague Mattmatt-falkner - Overview

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
matt-falkner - Overview

Solutions Architect @ BB. matt-falkner has 14 repositories available. Follow their code on GitHub.
 |

 |

 |



hopefully somewhere internally there is a normal "corporate" account we can pass this off to.  Matt will ask the open source team!
glad your doing well!
cheersed



    On Tuesday, March 21, 2023 at 11:19:03 a.m. EDT, Joe Delsol ***@***.***> wrote:  
 
 

Funny, I was not sure if there was anyone besides myself that could. 

Funny to see you are also still connected to this repo! Looks like you are doing fun things..

I’m doing good stuff at a Series A API Security company.

Ed,
Do you want to give us a couple accounts to add to this, so you are not looking for ghosts to merge, etc? Also, this is pushed to pypi; https://pypi.org/project/cyapi/

The doc error is over there, too.

I thought this project was getting replaced years ago. I knew about the issue you pushed, but had bitten off a documentation project that got away from me.. 

Let me know how I can help.

~~
Joe Delsol
916-802-7606

**Comment by rpermeh** [comment]
Kinda sad, but you can probably remove me.  Venture capital leaves little time for code review.Sent from iPhoneOn Mar 22, 2023, at 6:49 AM, Ed Bourne ***@***.***> wrote:﻿
 yes, please add me ebourne - Overview 

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
ebourne - Overview

ebourne has 5 repositories available. Follow their code on GitHub.
 |

 |

 |

and my colleague Mattmatt-falkner - Overview

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
matt-falkner - Overview

Solutions Architect @ BB. matt-falkner has 14 repositories available. Follow their code on GitHub.
 |

 |

 |



hopefully somewhere internally there is a normal "corporate" account we can pass this off to.  Matt will ask the open source team!
glad your doing well!
cheersed



    On Tuesday, March 21, 2023 at 11:19:03 a.m. EDT, Joe Delsol ***@***.***> wrote:  
 
 

Funny, I was not sure if there was anyone besides myself that could. 

Funny to see you are also still connected to this repo! Looks like you are doing fun things..

I’m doing good stuff at a Series A API Security company.

Ed,
Do you want to give us a couple accounts to add to this, so you are not looking for ghosts to merge, etc? Also, this is pushed to pypi; https://pypi.org/project/cyapi/

The doc error is over there, too.

I thought this project was getting replaced years ago. I knew about the issue you pushed, but had bitten off a documentation project that got away from me.. 

Let me know how I can help.

~~
Joe Delsol
916-802-7606

**Comment by joshlemos** [comment]
Gents - Great to see you’re still supporting this. I too should probably
not approve PRs at this point.

Best,
Josh

**Comment by joedelsol** [comment]
Josh,Great to hear from you.. are you suggesting it is past time to get us all out of these roles?I added Ed as Admin for CyAPI, but that is all I have control of.  Sorry for the delay, I was traveling this week.Once an admin, I’ll understand if you want to remove me, Ed.--Joe Delsol - 916-802-7606On Mar 22, 2023, at 7:54 AM, joshlemos ***@***.***> wrote:﻿
Gents - Great to see you’re still supporting this. I too should probably
not approve PRs at this point.

Best,
Josh

**Pull request merged**
